version: '3'

vars:
  CHATROOM_LINUX_PATH: ./chatroom_linux
  CHATROOM_WIN_PATH: ./chatroom.exe
  CONFIG_PATH: ./config/config.yml

tasks:

  build-chatroom:
    desc: "Build chatroom application on Linux and Windows"
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o chatroom_linux
      - GOOS=windows GOARCH=amd64 go build -o chatroom.exe

  run-chatroom-linux:
    desc: "Run chatroom application on Linux"
    cmds:
      - "export CONFIG_PATH={{.CONFIG_PATH}} && {{.CHATROOM_LINUX_PATH}}"

  run-chatroom-windows:
    desc: "Run chatroom application on Windows"
    cmds:
      - "export CONFIG_PATH={{.CONFIG_PATH}} && {{.CHATROOM_WIN_PATH}}"
