version: '3'

vars:
  CHAT_LINUX_PATH: ./chat/chat_linux
  CHAT_WIN_PATH: ./chat/chat.exe
  CHAT_NICK: test
  CHAT_ROOM: test

  CHATROOM_LINUX_PATH: ./frontend/chatroom_linux
  CHATROOM_WIN_PATH: ./frontend/chatroom.exe
  CONFIG_PATH: ./frontend/config/config.yml

tasks:
  build-chat:
    desc: "Build chat application on Linux and Windows"
    cmds:
      - cd chat; go build -o chat_linux
      - cd chat; GOOS=windows GOARCH=amd64 go build -o chat.exe

  build-chatroom:
    desc: "Build chatroom application on Linux and Windows"
    cmds:
      - cd frontend; go build -o chatroom_linux
      - cd frontend; GOOS=windows GOARCH=amd64 go build -o chatroom.exe

  run-chat-linux:
    desc: "Run chat application on Linux"
    cmds:
      - "{{.CHAT_LINUX_PATH}} -nick={{.CHAT_NICK}} -room={{.CHAT_ROOM}}"

  run-chat-linux-node:
    desc: "Run chat application as node on Linux"
    cmds:
      - "{{.CHAT_LINUX_PATH}} -nick={{.CHAT_NICK}} -room={{.CHAT_ROOM}} -node"

  run-chat-windows:
    desc: "Run chat application on Windows"
    cmds:
      - "{{.CHAT_WIN_PATH}} -nick={{.CHAT_NICK}} -room={{.CHAT_ROOM}}"

  run-chat-windows-node:
    desc: "Run chat application as node on Windows"
    cmds:
      - "{{.CHAT_WIN_PATH}} -nick={{.CHAT_NICK}} -room={{.CHAT_ROOM}} -node"

  run-chatroom-linux:
    desc: "Run chatroom application on Linux"
    cmds:
      - "export CONFIG_PATH={{.CONFIG_PATH}} && {{.CHATROOM_LINUX_PATH}}"

  run-chatroom-windows:
    desc: "Run chatroom application on Windows"
    cmds:
      - "export CONFIG_PATH={{.CONFIG_PATH}} && {{.CHATROOM_WIN_PATH}}"
