version: '3'

tasks:
  build-chat:
    desc: "Build chat application on Linux and Windows"
    cmds:
      - go build -o chat_linux
      - GOOS=windows GOARCH=amd64 go build -o chat.exe

  run-ai-bot:
    desc: "Run api server for AI bot in chats"
    cmds:
      - python3.9 main.py
