version: '3'

vars:
  CHAT_LINUX_PATH: ./chat/chat_linux
  CHAT_WIN_PATH: ./chat/chat.exe
  CHAT_NICK: test
  CHAT_ROOM: test

tasks:
  build-chat:
    desc: "Build chat application on Linux and Windows"
    cmds:
      - cd chat; go build -o chat_linux
      - cd chat; GOOS=windows GOARCH=amd64 go build -o chat.exe

  run-chat-linux:
    desc: "Run chat application on Linux"
    cmds:
      - "{{.CHAT_LINUX_PATH}} -nick={{.CHAT_NICK}} -room={{.CHAT_ROOM}}"

  run-chat-windows:
    desc: "Run chat application on Windows"
    cmds:
      - "{{.CHAT_WIN_PATH}} -nick={{.CHAT_NICK}} -room={{.CHAT_ROOM}}"